sonar.projectKey=billify
sonar.projectName=BILLIFY
sonar.sourceEncoding=UTF-8

sonar.sources=src,prisma
sonar.exclusions=**/node_modules/**,**/.next/**,**/*.d.ts,**/dist/**,public/**

sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.test.exclusions=**/node_modules/**

sonar.javascript.node.maxspace=4096
