-- AlterTable
ALTER TABLE "Business" ADD COLUMN "address" TEXT;
ALTER TABLE "Business" ADD COLUMN "phone" TEXT;
ALTER TABLE "Business" ADD COLUMN "tax_name" TEXT NOT NULL DEFAULT 'IVA';
ALTER TABLE "Business" ADD COLUMN "tax_rate" DOUBLE PRECISION NOT NULL DEFAULT 0;
